wandb_version: 1

T0:
  desc: null
  value: null
Tmult:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.17
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.17
      5: 0.10.21
      8:
      - 5
adam_l2:
  desc: null
  value: 1.0e-06
add_bn:
  desc: null
  value: true
arch:
  desc: null
  value: resnet18
bs:
  desc: null
  value: 128
byol_tau:
  desc: null
  value: 0.99
cj0:
  desc: null
  value: 0.4
cj1:
  desc: null
  value: 0.4
cj2:
  desc: null
  value: 0.4
cj3:
  desc: null
  value: 0.1
cj_p:
  desc: null
  value: 0.8
clf:
  desc: null
  value: sgd
clf_chkpt:
  desc: null
  value: ''
crop_r0:
  desc: null
  value: 0.75
crop_r1:
  desc: null
  value: 1.3333333333333333
crop_s0:
  desc: null
  value: 0.2
crop_s1:
  desc: null
  value: 1.0
dataset:
  desc: null
  value: imagenet
drop:
  desc: null
  value:
  - 50
  - 25
drop_gamma:
  desc: null
  value: 0.2
emb:
  desc: null
  value: 128
epoch:
  desc: null
  value: 200
eta_min:
  desc: null
  value: 0
eval_data:
  desc: null
  value: ''
eval_every:
  desc: null
  value: 20
eval_every_drop:
  desc: null
  value: 5
eval_head:
  desc: null
  value: false
evaluate:
  desc: null
  value: false
exp_id:
  desc: null
  value: HTBA_trigger_10_targeted_n02106550
fname:
  desc: null
  value: null
gs_p:
  desc: null
  value: 0.1
head_layers:
  desc: null
  value: 2
head_size:
  desc: null
  value: 1024
hf_p:
  desc: null
  value: 0.5
knn:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.002
lr_step:
  desc: null
  value: step
lr_warmup:
  desc: null
  value: true
method:
  desc: null
  value: byol
norm:
  desc: null
  value: true
num_samples:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 8
save_folder_root:
  desc: null
  value: save/
tau:
  desc: null
  value: 0.5
train_clean_file_path:
  desc: null
  value: /data/jianzhang/hrzhang/imagenet/imagenet100/train
train_file_path:
  desc: null
  value: ../poison-generation/data/HTBA_trigger_10_targeted_n02106550/train/loc_random_loc-min_0.25_loc-max_0.75_alpha_0.00_width_50_rate_1.00_targeted_True_filelist.txt
val_file_path:
  desc: null
  value: ../poison-generation/data/HTBA_trigger_10_targeted_n02106550/val_poisoned/loc_random_loc-min_0.10_loc-max_0.90_alpha_0.00_width_50_filelist.txt
val_poisoned_file_path:
  desc: null
  value: ''
w_eps:
  desc: null
  value: 0
w_iter:
  desc: null
  value: 1
w_size:
  desc: null
  value: 128
wandb:
  desc: null
  value: self_supervised
